# Generated by Django 5.1.6 on 2025-03-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='image',
        ),
    ]
