# Generated by Django 5.1.6 on 2025-03-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_rename_post_comment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image',
            new_name='post',
        ),
    ]
