# Generated by Django 5.1.6 on 2025-03-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_rename_image_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='image',
        ),
    ]
